In [ ]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris # iris dataseti
from sklearn.preprocessing import StandardScaler # ölçeklendirme

from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering

import warnings
warnings.filterwarnings('ignore')

In [16]:
iris = load_iris()
data = iris.data
label = iris.target

print(f"Veri şekli: {data.shape}")
print(f"Etiket şekli: {label.shape}")
print(f"Öznitelik isimleri: {iris.feature_names}")
print(f"Gerçek tür isimleri: {iris.target_names}")

Veri şekli: (150, 4)
Etiket şekli: (150,)
Öznitelik isimleri: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Gerçek tür isimleri: ['setosa' 'versicolor' 'virginica']


In [17]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print("Orijinal veri (ilk 5 satır):")
print(data[:5])
print("\nÖlçeklendirilmiş veri (ilk 5 satır):")
print(scaled_data[:5])

Orijinal veri (ilk 5 satır):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Ölçeklendirilmiş veri (ilk 5 satır):
[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]


In [18]:
kmeans = KMeans(n_clusters=3, random_state=42 , n_init = 10)

kmeans_labels = kmeans.fit_predict(data)
print("K-Means (ölçeksiz) sonuçları:")
print(kmeans_labels)

kmeans_labels_scaled = kmeans.fit_predict(scaled_data)
print("K-Means (ölçekli) sonuçları:")
print(kmeans_labels_scaled)

K-Means (ölçeksiz) sonuçları:
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]
K-Means (ölçekli) sonuçları:
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 0 0 0 2 0 0 0 0 0 0 0 0 2 0 0 0 0 2 0 0 0
 0 2 2 2 0 0 0 0 0 0 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 2 2 2 2 2 2 0 0 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]


In [19]:
kmeans_crosstab = pd.crosstab(label, kmeans_labels)
kmeans_crosstab_scaled = pd.crosstab(label, kmeans_labels_scaled)

print("Sütunlar: K-Means'in bulduğu kümeler (0, 1, 2)")
print("Satırlar: Gerçek Türler (0: Setosa, 1: Versicolor, 2: Virginica)\n")

print("K-Means (ölçeksiz) Karşılaştırma Tablosu:")
print(kmeans_crosstab)

print("\nK-Means (ölçekli) Karşılaştırma Tablosu:")
print(kmeans_crosstab_scaled)

Sütunlar: K-Means'in bulduğu kümeler (0, 1, 2)
Satırlar: Gerçek Türler (0: Setosa, 1: Versicolor, 2: Virginica)

K-Means (ölçeksiz) Karşılaştırma Tablosu:
col_0   0   1   2
row_0            
0       0  50   0
1      48   0   2
2      14   0  36

K-Means (ölçekli) Karşılaştırma Tablosu:
col_0   0   1   2
row_0            
0       0  50   0
1      39   0  11
2      14   0  36


In [20]:
agg_cluster = AgglomerativeClustering(n_clusters=3)

agg_labels = agg_cluster.fit_predict(data)
print("Hiyerarşik Kümeleme (ölçeksiz) sonuçları:")
print(agg_labels)

agg_labels_scaled = agg_cluster.fit_predict(scaled_data)
print("Hiyerarşik Kümeleme (ölçekli) sonuçları:")
print(agg_labels_scaled)

Hiyerarşik Kümeleme (ölçeksiz) sonuçları:
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 0 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]
Hiyerarşik Kümeleme (ölçekli) sonuçları:
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 0 0 0 2 0 2 0 2 0 2 2 0 2 0 2 0 2 2 2 2 0 0 0 0
 0 0 0 0 0 2 2 2 2 0 2 0 0 2 2 2 2 0 2 2 2 2 2 0 2 2 0 0 0 0 0 0 2 0 0 0 0
 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]


In [21]:
agg_crosstab = pd.crosstab(label, agg_labels)
agg_crosstab_scaled = pd.crosstab(label, agg_labels_scaled)

print("Sütunlar: Hiyerarşik Kümeleme'nin bulduğu kümeler (0, 1, 2)")
print("Satırlar: Gerçek Türler (0: Setosa, 1: Versicolor, 2: Virginica)")

print("\nHiyerarşik Kümeleme (ölçeksiz) Karşılaştırma Tablosu:")
print(agg_crosstab)

print("\nHiyerarşik Kümeleme (ölçekli) Karşılaştırma Tablosu:")
print(agg_crosstab_scaled)

Sütunlar: Hiyerarşik Kümeleme'nin bulduğu kümeler (0, 1, 2)
Satırlar: Gerçek Türler (0: Setosa, 1: Versicolor, 2: Virginica)

Hiyerarşik Kümeleme (ölçeksiz) Karşılaştırma Tablosu:
col_0   0   1   2
row_0            
0       0  50   0
1      49   0   1
2      15   0  35

Hiyerarşik Kümeleme (ölçekli) Karşılaştırma Tablosu:
col_0   0   1   2
row_0            
0       0  49   1
1      23   0  27
2      48   0   2
